### ISSUE TITLE
not compatible with Swift 3??

### ISSUE THREAD

**Issue by zfrankz** [numen31337/AKVideoImageView#2]
I'm having issues when trying to use this library with swift 3. First, complainig about NSURL (now named URL) and also, once removed the asserts for NSURL, I receive an error:
"[AVAssetReaderTrackOutput initWithTrack:outputSettings:] invalid parameter not satisfying: track != ((void *)0)"

help?

**Comment by numen31337** [comment]
Hey @zfrankz. I will look into this today

**Comment by numen31337** [comment]
Just checked, everything is working fine for me, here is the example of the swift code:
```swift
import UIKit
import AKVideoImageView

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let url = Bundle.main.url(forResource: "video_1", withExtension: "mp4")
        let videoView = AKVideoImageView(frame: view.bounds, videoURL: url!)!
        view.addSubview(videoView)
    }

}
```

Let me know if you still have some issues with this

**Comment by zfrankz** [comment]
I'm trying to use it on a UITableViewCell subclass and I'm getting a crash and the message: "*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVAssetReaderTrackOutput initWithTrack:outputSettings:] invalid parameter not satisfying: track != ((void *)0)'"

my code:
`func loadInfo() {
        let url = Bundle.main.url(forResource: "video1_edit", withExtension: "mp4")
        let videoView = AKVideoImageView(frame: CGRect(x: 0, y: 0, width: 320, height: 178), videoURL: url!)
        self.contentView.addSubview(videoView!)
    }`
I've tried adding the subview to self and self.contentView and same result

**Comment by zfrankz** [comment]
Fixed, It was an issue with an object in my InterfaceBuilder.
