### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by furueili** [numen31337/AKVideoImageView#3]
crash issue like below:
Thumbnail image generation error Error Domain=AVFoundationErrorDomain Code=-11839 "無法解碼" UserInfo={NSUnderlyingError=0x1356ce6a0 {Error Domain=NSOSStatusErrorDomain Code=-12913 "(null)"}, NSLocalizedFailureReason=此媒體所需的解碼器忙碌中。, NSLocalizedRecoverySuggestion=停止其他解碼媒體的動作，然後再試一次。, NSLocalizedDescription=無法解碼}
Please give me some help thx

**Comment by numen31337** [comment]
Could you please provide some more detailed info, at least stack trace, an example would be perfect.

**Comment by furueili** [comment]
Touch button to present this ViewController with the AKVideoImageView and then dismiss it through another button ; repeates this action maybe ten times and then the app crash

**Comment by numen31337** [comment]
Ok I'll look into this issue these days, could you provide me with a stack trace, this should help

**Comment by furueili** [comment]
would u tell me how to get the stack trace? many thanks

**Comment by numen31337** [comment]
Have breakpoints enabled:
![](https://preview.ibb.co/dJPfL5/Screen_Shot_2017_06_27_at_1_00_29_PM.png)

Then when it crashes make a screenshot of the stack:
![](https://preview.ibb.co/gbRc05/Screen_Shot_2017_06_27_at_12_59_30_PM.png)

**Comment by numen31337** [comment]
No feedback, closing
