### ISSUE TITLE
load video with URL not working  

### ISSUE THREAD

**Issue by patelmayank** [numen31337/AKVideoImageView#4]
When I tried to use video via link then it is crashing 

      NSURL *videoURL = [NSURL URLWithString:@"http://www.webestools.com/page/media/videoTag/BigBuckBunny.mp4"];
    
      AKVideoImageView *videoBG = [[AKVideoImageView alloc] initWithFrame:self.view.bounds
                                                               videoURL:videoURL];

Crash log 

Thumbnail image generation error Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSUnderlyingError=0x600000240e70 {Error Domain=NSOSStatusErrorDomain Code=-1022 "(null)"}, NSLocalizedFailureReason=An unknown error occurred (-1022), NSLocalizedDescription=The operation could not be completed}
2017-08-09 11:57:15.747 Example[15354:280879] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVAssetReaderTrackOutput initWithTrack:outputSettings:] invalid parameter not satisfying: track != ((void *)0)'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105832b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000104f27141 objc_exception_throw + 48
	2   AVFoundation                        0x00000001054815ea -[AVAssetReaderTrackOutput dealloc] + 0
	3   AVFoundation                        0x000000010548118d +[AVAssetReaderTrackOutput assetReaderTrackOutputWithTrack:outputSettings:] + 62
	4   Example                             0x0000000104951ba5 -[AKVideoImageView createAssetReader] + 1045
	5   Example                             0x00000001049520a6 -[AKVideoImageView playVideo] + 870
	6   Example                             0x000000010495150b -[AKVideoImageView didMoveToSuperview] + 43
	7   UIKit                               0x000000010650fb53 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 932
	8   UIKit                               0x000000010650f72d -[UIView(Hierarchy) _postMovedFromSuperview:] + 828
	9   UIKit                               0x000000010651f6ba -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1927
	10  UIKit                               0x000000010650d9a8 -[UIView(Hierarchy) addSubview:] + 838
	11  Example                             0x0000000104950812 -[ViewController viewDidLoad] + 370
	12  UIKit                               0x0000000106602cca -[UIViewController loadViewIfRequired] + 1235
	13  UIKit                               0x000000010660310a -[UIViewController view] + 27
	14  UIKit                               0x00000001064cb63a -[UIWindow addRootViewControllerViewIfPossible] + 65
	15  UIKit                               0x00000001064cbd20 -[UIWindow _setHidden:forced:] + 294
	16  UIKit                               0x00000001064deb6e -[UIWindow makeKeyAndVisible] + 42
	17  UIKit                               0x000000010645831f -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4346
	18  UIKit                               0x000000010645e584 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1709
	19  UIKit                               0x000000010645b793 -[UIApplication workspaceDidEndTransaction:] + 182
	20  FrontBoardServices                  0x000000010b0de5f6 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	21  FrontBoardServices                  0x000000010b0de46d -[FBSSerialQueue _performNext] + 186
	22  FrontBoardServices                  0x000000010b0de7f6 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	23  CoreFoundation                      0x00000001057d8c01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00000001057be0cf __CFRunLoopDoSources0 + 527
	25  CoreFoundation                      0x00000001057bd5ff __CFRunLoopRun + 911
	26  CoreFoundation                      0x00000001057bd016 CFRunLoopRunSpecific + 406
	27  UIKit                               0x000000010645a02f -[UIApplication _run] + 468
	28  UIKit                               0x00000001064600d4 UIApplicationMain + 159
	29  Example                             0x0000000104953acf main + 111
	30  libdyld.dylib                       0x0000000108f3165d start + 1
	31  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by numen31337** [comment]
This library uses AVAssetReader to render video frames which is supporting only local URL's and returns error: "Cannot initialize an instance of AVAssetReader with an asset at non-local URL" if you trying to read any remote URL.
