### ISSUE TITLE
Add some code for a better integration in storyboards

### ISSUE THREAD

**Issue by cutmaster** [numen31337/AKVideoImageView#5]
Your class is very cool.
Otherwise, it can be better if used by the integration directly in the storyboard (change UIImageView into AKVideoImageView).
To do so, it is necessary to test that the videoURL can be nul inside the playvideo method, then to add the ability to call playVideo on the setVideoURL method if the previous instance of videoURL was nil.

**Comment by numen31337** [comment]
I've implemented the feature. Thank you for the request.
