### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by cutmaster** [numen31337/AKVideoImageView#6]
When leaving AKVideoImageView runnin & runnin, and worse with 2 or 3 differents AKVideoImageView looping on a video, the memory used is always increasing...

**Comment by numen31337** [comment]
Hey @cutmaster, looks like I can't reproduce this leak. Could you please provide me with some sample project where I can see this leak and debug it.
Here are 2 minutes of the sample project activity on my device:
![ScreenShot](https://i.imgur.com/bJOc3zq.png])

**Comment by numen31337** [comment]
No feedback, closing
